"""
Generate rtl/dec8b10b_rom.svh: the 8b/10b decode ROM as inline assignments,
`include-d into an initial block in dec8b10b.sv. One entry per 10-bit codeword
(index 0..1023, MSB = a = first bit on the wire).

Each 10-bit ROM entry is {valid[1], k[1], data[7:0]}:
  valid = 1 if the codeword is a legal 8b/10b symbol, else 0
  k     = 1 for a control symbol
  data  = decoded 8-bit character ({H G F E D C B A})

A generated `include (resolved at compile time relative to the source dir) is
used instead of $readmemb to avoid Windows/Icarus runtime path quirks.

Regenerate whenever tb/model_8b10b.py changes:
    python scripts/gen_dec_rom.py
The reference model self-tests its tables on import, so a bad table can't
silently produce a bad ROM.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tb"))

from model_8b10b import decode   # noqa: E402  (path set above)

OUT = ROOT / "rtl" / "dec8b10b_rom.svh"


def main():
    lines = ["// Auto-generated by scripts/gen_dec_rom.py -- do not edit."]
    valid = 0
    for i in range(1024):
        cw = format(i, "010b")          # cw[0] = a = MSB, matches data_in[9]
        hit = decode(cw)
        if hit is None:
            bits = "0000000000"         # valid=0
        else:
            byte, k = hit
            bits = "1" + ("1" if k else "0") + format(byte, "08b")
            valid += 1
        lines.append(f"rom[{i}] = 10'b{bits};")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} (1024 entries, {valid} valid)")


if __name__ == "__main__":
    main()
